### ISSUE TITLE
💬 [Question] Ist es möglich auch ohne Registrierung zu spielen?

### ISSUE THREAD

**Issue by ulfgebhardt** [fake-oder-news/fake-oder-news#31]
### Ist es möglich auch ohne Registrierung zu spielen?

@weckermacher fragt ob es auch möglich sei das Spiel zu spielen ohne sich zu registrieren (nicht nur die 3 Beispiel Fragen).

Was sind die Einschränkungen, wenn wir keine Registrierung verlangen?
Wofür brauchen wir EMail, Nutzername und PW?

### Additional context

Einschränkungen wären:
- Kann keine EMail schicken
- Kann keine Highscore mit namen anzeigen
- Kann Gerät nicht (so einfach) wechseln

**Comment by visionmakery** [comment]
Ich würde das einfach nicht ermöglichen. Wir machen uns damit nur ein Fass auf. Spontan fallen mir folgende Fragen ein: 

- Wie bestätigt dieser Nutzer die Nutzungsbedingungen? 
- Wie soll dieser Nutzer mit Freunden Pakete kaufen / spielen?

**Comment by visionmakery** [comment]
weitere Argumente dagegen von heute @weckermacher:
- Kontaktmöglichkeit des Nutzers (E-Mail) wird nicht erhoben
- Content-Algorithmus kann nicht optimieren (Abbruchrate, Heat-Mapping,...)
- Account-Persistenz (gespielte Fragen, Scoring,...) kann nicht garantiert werden, z.B. bei Löschen der App
- Daten werden auf des Nutzers Handy und nicht auf unserem Server gespeichert – wo besteht der Unterschied (für Skeptiker), wenn die Überwachung allumfassend ist?
- Die entstehenden Daten sind nicht so sensibel wie bei DEMOCRACY
- Erfahrungen aus DEMOCRACY: keine Daten über den Nutzer zu sammeln, erschwert die Entwicklung und das Testing

**Comment by visionmakery** [comment]
Lösung

- kein Spielen ohne Registratur, aber...

- total transparenter Umgang mit Data Policy 
- interne Leitlinie: Wofür brauchen wir diese Daten?
- externe Leitlinie: Erklären!
- "Wohin gehen Deine Daten?" beim OnBoarding 
- Visualisierung der Datenströme
